### ISSUE TITLE
Bug: Markdown: JS/JSX Codeblock return is not displayed.

### ISSUE THREAD

**Issue by ShubhamVerma1811** [uiwjs/react-textarea-code-editor#101]
Steps to reproduce:
1. Go to the link and select markdown https://uiwjs.github.io/react-textarea-code-editor/
2. Paste in the below code

```js
const Comp = () => {
return <IAmHidden/>
}
```

```jsx
const Comp = () => {
return <IAmAlsoHidden></IAmAlsoHidden>
}

```

Expectation:
Syntax highlight should detect return type component

![image](https://user-images.githubusercontent.com/25576658/158005846-816d298e-cd40-4387-9d1d-90f84d2f02ba.png)

**Comment by ShubhamVerma1811** [comment]
Looks like it's not just js jsx

Anything between `<>` causes the issue inside the codeblocks

**Comment by jaywcjlove** [comment]
@ShubhamVerma1811 Upgrade `v1.5.2`

**Comment by ShubhamVerma1811** [comment]
Can confirm it's fixed!

Thank you!
