### ISSUE TITLE
Placeholder behavior not as expected

### ISSUE THREAD

**Issue by leonardomathon** [uiwjs/react-textarea-code-editor#131]
I just upgraded to version 2.0.3 and the behavior of the placeholder seems to have changed in version 2.0.2 (I believe due to #114).

**Behavior prior to 2.0.2**
When the placeholder attribute was set, the `<code>` element was empty until a value is set. The placeholder text is a different, darker color than the actual text color, as it should be.
![image](https://user-images.githubusercontent.com/30813241/198144999-885b79b9-5f64-40a1-b088-88b524995042.png)

**Behavior after 2.0.2**
When the placeholder is set and no value is specified, the placeholder is also listed in the `<code>` tag, so it overlays the actual placeholder. This means that the color is not as dark as it used to be and for some reason, the edges of the font seem rougher (not noticeable in screenshot).
![image](https://user-images.githubusercontent.com/30813241/198145745-e847eb29-938d-47e1-b73e-f7ae56f65c66.png)

Is there a way I can not add the value of the placeholder to the `<code>` tag, so that the behavior stays the same like versions before 2.0.3?

**Comment by jaywcjlove** [comment]
@leonardomathon oh, i fixed it.

**Comment by leonardomathon** [comment]
@jaywcjlove awesome, though, the release CI failed

**Comment by jaywcjlove** [comment]
@leonardomathon CI passed.

**Comment by leonardomathon** [comment]
Thanks, it's fixed.
