### ISSUE TITLE
Text overflow not working

### ISSUE THREAD

**Issue by rbro3551** [uiwjs/react-textarea-code-editor#133]
Whenever I add “overflow:”auto”” to the style in this with a fixed height, the text seems to overlap itself and get messed up as if it’s coming back down from the top as seen in the picture. Is there a way to properly have an overflow scroll here?
![image](https://user-images.githubusercontent.com/30447344/206085433-1bf52fa1-aee8-4f55-8e07-3e10926c332c.jpg)

**Comment by jaywcjlove** [comment]
@rbro3551 Style conflict.

**Comment by rbro3551** [comment]
> @rbro3551 Style conflict.

Thank you for the reply! I did try starting a bare project and just having a codeEditor by itself without any other styles and it gave me the same issue. There's a picture of the styling I had below. This would definitely be something on my end though?
![image](https://user-images.githubusercontent.com/30447344/206095979-62825a3c-0deb-4a83-a712-ae201d4020dc.jpeg)

**Comment by jaywcjlove** [comment]
You can use [codesandbox.io](https://codesandbox.io/embed/react-textarea-code-editor-for-example-mcebp?fontsize=14&hidenavigation=1&theme=dark) to provide me with an example to reproduce the error. I can help you look

**Comment by rbro3551** [comment]
> You can use [codesandbox.io](https://codesandbox.io/embed/react-textarea-code-editor-for-example-mcebp?fontsize=14&hidenavigation=1&theme=dark) to provide me with an example to reproduce the error. I can help you look

Here is the link with the issue: https://codesandbox.io/s/goofy-butterfly-wp8bm2?

Thanks!

**Comment by jaywcjlove** [comment]
@rbro3551 Do you need a horizontal scroll bar?

**Comment by rbro3551** [comment]
> @rbro3551 Do you need a horizontal scroll bar?

No my issue is with vertical scrolling. When the text overflows vertically that's when it messes up

**Comment by jaywcjlove** [comment]
@rbro3551 https://codesandbox.io/embed/uiwjs-react-textarea-code-editor-issues-133-zq9vpw?fontsize=14&hidenavigation=1&theme=dark

**Comment by jaywcjlove** [comment]
```jsx
<div style={{ height: 130, overflow: "auto" }}>
  <CodeEditor
    value={code}
    ref={textRef}
    language="js"
    placeholder="Please enter JS code."
    onChange={(evn) => setCode(evn.target.value)}
    padding={15}
    style={{
      fontFamily:
        "ui-monospace,SFMono-Regular,SF Mono,Consolas,Liberation Mono,Menlo,monospace",
      fontSize: 12
    }}
  />
</div>
```

@rbro3551

**Comment by rbro3551** [comment]
> ```jsx
> 
> <div style={{ height: 130, overflow: "auto" }}>
> 
>   <CodeEditor
> 
>     value={code}
> 
>     ref={textRef}
> 
>     language="js"
> 
>     placeholder="Please enter JS code."
> 
>     onChange={(evn) => setCode(evn.target.value)}
> 
>     padding={15}
> 
>     style={{
> 
>       fontFamily:
> 
>         "ui-monospace,SFMono-Regular,SF Mono,Consolas,Liberation Mono,Menlo,monospace",
> 
>       fontSize: 12
> 
>     }}
> 
>   />
> 
> </div>
> 
> ```
> 
> 
> 
> @rbro3551 

Oh wow that works great thank you so much!
