### ISSUE TITLE
Auto comment selection

### ISSUE THREAD

**Issue by lucasmrl** [uiwjs/react-textarea-code-editor#145]
Hi!

Is it possible to implement something similar to https://www.jetbrains.com/help/mps/commenting-and-uncommenting-blocks-of-code.html?
By pressing some shortcut defined by us, the code selected will be commented out.

Thanks!

**Comment by jaywcjlove** [comment]
This is a simple code editor, it is very difficult to implement this function


You can try to use https://github.com/uiwjs/react-codemirror

@lucasmrl

**Comment by lucasmrl** [comment]
Got it! Thank you for the response!
