### ISSUE TITLE
Disable prop

### ISSUE THREAD

**Issue by clay53** [uiwjs/react-textarea-code-editor#153]
Add prop to allow disabling the code editor (not-editable)

**Comment by jaywcjlove** [comment]
@clay53 https://codesandbox.io/embed/https-github-com-uiwjs-react-textarea-code-editor-issues-153-7694n4?fontsize=14&hidenavigation=1&theme=dark

```diff
<CodeEditor
  value={code}
  language="js"
  placeholder="Please enter JS code."
  padding={15}
+  readOnly
/>
```

**Comment by clay53** [comment]
> @clay53 https://codesandbox.io/embed/https-github-com-uiwjs-react-textarea-code-editor-issues-153-7694n4?fontsize=14&hidenavigation=1&theme=dark
> 
> ```diff
> <CodeEditor
>   value={code}
>   language="js"
>   placeholder="Please enter JS code."
>   padding={15}
> +  readOnly
> />
> ```

Oh, thank you lol
