### ISSUE TITLE
The code editor doesn't format numbers well

### ISSUE THREAD

**Issue by kmartin62** [uiwjs/react-textarea-code-editor#22]
Single numbers won't format well as it increases their size and it changes the color to red (I assume the color changing is part of the code editor so that's not a problem). I tried it with multiple languages and it doesn't work good for all of them. However, having the numbers next to a string, the problem doesn't occur.
![bug number](https://user-images.githubusercontent.com/26507591/130428982-992092ab-4713-4c41-9a30-a5342fd47b24.png)

**Comment by jaywcjlove** [comment]
@kmartin62 I didn't understand what it meant.

**Comment by kmartin62** [comment]
@jaywcjlove it means that when I type numbers, it increases their size and it doesn't look good. See the photo attached, I typed function (1) but the following output wasn't as it should be

**Comment by jaywcjlove** [comment]
![image](https://user-images.githubusercontent.com/1680273/130434422-a9fc4de3-8c52-4a85-83ef-7f16291cb172.png)

@kmartin62 Is there a style conflict?

**Comment by kmartin62** [comment]
@jaywcjlove hm, seems so. What could be the issue on my side, any ideas? From what you showed me, looks like it works good on your side

**Comment by jaywcjlove** [comment]
@kmartin62 https://codesandbox.io/embed/react-textarea-code-editor-for-example-mcebp?fontsize=14&hidenavigation=1&theme=dark

You can create a debugging example.

**Comment by kmartin62** [comment]
@jaywcjlove Never mind, I found the error. The style for the class `.number` had a big font-size set for it.
