### ISSUE TITLE
[Feature Request] allow to change theme colors

### ISSUE THREAD

**Issue by juanlatorre** [uiwjs/react-textarea-code-editor#43]
Hi, extending the theme can be an interesting feature, currently I change the background using chakra-ui color mode to achieve something like this:

![image](https://user-images.githubusercontent.com/4494526/132865064-3f5b89d9-81cf-4e1a-ae9a-18d7993a704c.png)
![image](https://user-images.githubusercontent.com/4494526/132865122-c2cd58b1-3682-4a02-a7b5-6023baca97cb.png)

But when I wrote code on the box..

![image](https://user-images.githubusercontent.com/4494526/132865208-d992c0e7-bc0b-452d-946c-b2484954f2ca.png)

Is it possible to customize the syntax highlight colors?

**Comment by jaywcjlove** [comment]
@juanlatorre You can customize the syntax highlighting color.

[@uiw/react-textarea-code-editor/dist.css](https://uiwjs.github.io/npm-unpkg/#/pkg/@uiw/react-textarea-code-editor@1.4.9/file/dist.css)

**Comment by juanlatorre** [comment]
> @juanlatorre You can customize the syntax highlighting color.
> 
> [@uiw/react-textarea-code-editor/dist.css](https://uiwjs.github.io/npm-unpkg/#/pkg/@uiw/react-textarea-code-editor@1.4.9/file/dist.css)

omg, you are right, thanks !
