### ISSUE TITLE
[Feature Request] Option to use custom highlighters

### ISSUE THREAD

**Issue by kimyoonduk** [uiwjs/react-textarea-code-editor#60]
Hi, I came over from https://github.com/satya164/react-simple-code-editor/.

My use case involves highlighting certain words using a custom function.
The highlighting in this version seems to be abstracted so that only language inputs to prism are allowed.
Would it be possible to add an option to use a custom highlighter?

**Comment by jaywcjlove** [comment]
It is not recommended to do this, it will cause a huge volume of bundle.

@kimyoonduk 

Code highlighting is integrated by default for convenience. But it can be extracted and customized.

**Comment by jaywcjlove** [comment]
@kimyoonduk Added `rehypePlugins` props, But this is not recommended.


- [**`rehype-prism`**](https://github.com/mapbox/rehype-prism) (__default integration__) — syntax highlighting with Prism via refractor
- [rehype-highlight](https://github.com/rehypejs/rehype-highlight) — syntax highlight code blocks with Highlight.js via lowlight
- [rehype-highlight-code-block](https://github.com/mapbox/rehype-highlight-code-block) — syntax highlight code blocks with any function you provide
- [rehype-prism-plus](https://github.com/timlrx/rehype-prism-plus) — syntax highlighting with Prism via refractor with extras
- [rehype-shiki](https://github.com/rsclarke/rehype-shiki) — syntax highlight code blocks with Shiki

**Comment by kimyoonduk** [comment]
Thank you so much!
