### ISSUE TITLE
jest unexpected token

### ISSUE THREAD

**Issue by marabesi** [uiwjs/react-textarea-code-editor#68]
Hello there, I am trying to use this editor for my project, but I am facing the following issue:

![image](https://user-images.githubusercontent.com/2129872/137094107-5215dd45-5e6c-4f47-840c-08542ecf50c5.png)

it happens if I add  the lib and run the tests I have in place, I amusing a reactjs app created using CRA.

It works on the real app, so I guess this is something related to jest only?

![image](https://user-images.githubusercontent.com/2129872/137094376-96607641-957e-4804-a116-ce8b81fe0cc1.png)

Repo with reproducible code: https://github.com/marabesi/json-utility-tool/tree/feat/textarea-editor

action failing: https://github.com/marabesi/json-utility-tool/runs/3880042855#step:7:54

**Comment by marabesi** [comment]
Thanks for the quick response @jaywcjlove , you are correct, it fixed the issue, closing this one then :)

**Comment by christianjtr** [comment]
Hi! .... First of all, nice job.

I am facing the same problem, however, I could not solve it in this way yet.

I'm working in a monorepo, so I added the config to the global **`jest.config.js`** (jest version: 25.5.4)

```
module.exports = {
   projects: [{
      ...
      transformIgnorePatterns: ['<rootDir>/[PATH_TO_MY_APP]/node_modules/?!(.*)'],
      ...
   }]
}
```

Any suggestion?. Thanks in advance.
