### ISSUE TITLE
Dark mode

### ISSUE THREAD

**Issue by marabesi** [uiwjs/react-textarea-code-editor#73]
Is there a way to use custom styles for the text area?

**Comment by jaywcjlove** [comment]
You can override the style. You can also rewrite the style.

https://uiwjs.github.io/npm-unpkg/#/pkg/@uiw/react-textarea-code-editor/file/esm/style/index.css

Use the babel plugin [`babel-plugin-transform-remove-imports`](https://github.com/uiwjs/babel-plugin-transform-remove-imports) to delete the css style in the package.

@marabesi
