### ISSUE TITLE
Disabling line wrap for long lines

### ISSUE THREAD

**Issue by itssimon** [uiwjs/react-textarea-code-editor#76]
Is there any way to disable line wrapping within the editor and have horizontal scrolling instead? This would be important for editing YAML containing long strings.

**Comment by jaywcjlove** [comment]
@itssimon This will complicate the editor. If you need to use more complex functions, you can choose [`@uiw/react-codemirror`](https://github.com/uiwjs/react-codemirror), [`@uiw/react-monacoeditor`](https://github.com/jaywcjlove/react-monacoeditor).
