### ISSUE TITLE
Very Slow in Safari

### ISSUE THREAD

**Issue by NicholasLYang** [uiwjs/react-textarea-code-editor#96]
Hi, this editor looks great. Unfortunately, it seems to run really slowly in Safari. Either that or updates are not being painted immediately.

Thanks,
Nicholas

**Comment by jaywcjlove** [comment]
I tested it and it doesn't seem to be a problem.
@NicholasLYang

**Comment by NicholasLYang** [comment]
Hmm okay. Well Safari support is not high on our priorities so I'll close this for now.
